name: notapp
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  fluttertoast: ^8.2.8
  font_awesome_flutter: ^10.7.0
  get_it: ^7.7.0
  go_router: ^13.1.0
  intl: ^0.19.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  motion_toast: ^2.11.0
  path_provider: ^2.1.4

dev_dependencies:
  build_runner: ^2.4.11
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true
